/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.systemacademy.telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo-Notebook
 */
public class telaPrincpal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincpal
     */
    public telaPrincpal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        desktop = new javax.swing.JDesktopPane();
        Menu = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        menCadAlu = new javax.swing.JMenuItem();
        MenCadPer = new javax.swing.JMenuItem();
        menCadContro = new javax.swing.JMenu();
        MenuCadAluno = new javax.swing.JMenuItem();
        menOpc = new javax.swing.JMenu();
        MenOpcSai = new javax.swing.JMenuItem();
        menCadAju = new javax.swing.JMenu();
        MenCadSob = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema para Controle de OS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        menCad.setText(" Cadastro");

        menCadAlu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menCadAlu.setText("Usuário");
        menCadAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadAluActionPerformed(evt);
            }
        });
        menCad.add(menCadAlu);

        MenCadPer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        MenCadPer.setText("Código de Confirmação");
        MenCadPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadPerActionPerformed(evt);
            }
        });
        menCad.add(MenCadPer);

        Menu.add(menCad);

        menCadContro.setText("Controle");

        MenuCadAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        MenuCadAluno.setText("Usuários");
        MenuCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadAlunoActionPerformed(evt);
            }
        });
        menCadContro.add(MenuCadAluno);

        Menu.add(menCadContro);

        menOpc.setText("Opções");

        MenOpcSai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        MenOpcSai.setText("Sair");
        MenOpcSai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenOpcSaiActionPerformed(evt);
            }
        });
        menOpc.add(MenOpcSai);

        Menu.add(menOpc);

        menCadAju.setText("Ajuda");

        MenCadSob.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        MenCadSob.setText("Sobre");
        MenCadSob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadSobActionPerformed(evt);
            }
        });
        menCadAju.add(MenCadSob);

        Menu.add(menCadAju);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        setSize(new java.awt.Dimension(1016, 542));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menCadAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadAluActionPerformed
        // as linhas abaixo vão abrir o form TelaAlunos dentro do destop pane:
        TelaControlUsers controle= new TelaControlUsers();
        controle.setVisible(true);
        desktop.add(controle);
    }//GEN-LAST:event_menCadAluActionPerformed

    private void MenCadPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadPerActionPerformed
        // Chamar tela cadastro usuario
        TelaCadCod aluno= new TelaCadCod();
        aluno.setVisible(true);
        desktop.add(aluno);
    }//GEN-LAST:event_MenCadPerActionPerformed

    private void MenuCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadAlunoActionPerformed
        // chamar tela de controle
        
    }//GEN-LAST:event_MenuCadAlunoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        
    }//GEN-LAST:event_formWindowActivated

    private void MenOpcSaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenOpcSaiActionPerformed
        // exibe uma caixa de dialogo:
        int sair=JOptionPane.showConfirmDialog(null,"tem certeza que deseja sair?","Atenção",JOptionPane.YES_NO_OPTION);
        if (sair ==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_MenOpcSaiActionPerformed

    private void MenCadSobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadSobActionPerformed
        // chamando a tela sobre:
        TelaSobre sobre= new TelaSobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_MenCadSobActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenCadPer;
    private javax.swing.JMenuItem MenCadSob;
    private javax.swing.JMenuItem MenOpcSai;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem MenuCadAluno;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu menCad;
    private javax.swing.JMenu menCadAju;
    private javax.swing.JMenuItem menCadAlu;
    private javax.swing.JMenu menCadContro;
    private javax.swing.JMenu menOpc;
    // End of variables declaration//GEN-END:variables
}
